-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd([[highlight clear]])

local highlight = function(group, bg, fg, attr)
  fg = fg and "guifg=" .. fg or ""
  bg = bg and "guibg=" .. bg or ""
  attr = attr and "gui=" .. attr or ""

  vim.api.nvim_command("highlight " .. group .. " " .. fg .. " " .. bg .. " " .. attr)
end

local link = function(target, group)
  vim.api.nvim_command("highlight! link " .. target .. " " .. group)
end

local Color3 = "#FF0000"
local Color2 = "#800080"
local Color1 = "#0078d7"
local Color4 = "#000000"
local Color0 = "#cd3131"

highlight("Error", nil, Color0, nil)
highlight("Comment", nil, Color1, "italic")
highlight("Number", nil, Color2, nil)
highlight("Operator", nil, Color3, "bold")
highlight("Keyword", nil, Color4, "bold")
highlight("Conditional", nil, Color4, "bold")
highlight("Repeat", nil, Color4, "bold")

link("Folded", "Comment")
link("TSTag", "MyTag")
link("TSConstBuiltin", "TSVariableBuiltin")
link("Whitespace", "Comment")
link("TSConditional", "Conditional")
link("TSOperator", "Operator")
link("TSProperty", "TSField")
link("NonText", "Comment")
link("TSFunction", "Function")
link("TSParameterReference", "TSParameter")
link("TSComment", "Comment")
link("TSPunctBracket", "MyTag")
link("TSRepeat", "Repeat")
link("Conditional", "Operator")
link("TSField", "Constant")
link("Operator", "Keyword")
link("CursorLineNr", "Identifier")
link("TSPunctSpecial", "TSPunctDelimiter")
link("TSParameter", "Constant")
link("Repeat", "Conditional")
link("TSNamespace", "TSType")
link("TSFloat", "Number")
link("TSTagDelimiter", "Type")
link("TSKeyword", "Keyword")
link("TelescopeNormal", "Normal")
link("TSNumber", "Number")
link("TSType", "Type")
link("TSString", "String")
link("Macro", "Function")
link("TSLabel", "Type")
link("TSFuncMacro", "Macro")
link("TSConstant", "Constant")
