-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd([[highlight clear]])
vim.o.background = "light"

local highlight = function(group, bg, fg, attr)
  fg = fg and "guifg=" .. fg or ""
  bg = bg and "guibg=" .. bg or ""
  attr = attr and "gui=" .. attr or ""

  vim.api.nvim_command("highlight " .. group .. " " .. fg .. " " .. bg .. " " .. attr)
end

local link = function(target, group)
  vim.api.nvim_command("highlight! link " .. target .. " " .. group)
end

local Color5 = "#FFFFFF"
local Color0 = "#cd3131"
local Color2 = "#800080"
local Color3 = "#FF0000"
local Color1 = "#0078d7"
local Color4 = "#000000"
local Color6 = "#0000FF"

highlight("Normal", nil, Color4, nil)
highlight("Special", nil, Color4, nil)
highlight("Error", nil, Color0, nil)
highlight("Comment", nil, Color1, "italic")
highlight("Number", nil, Color2, nil)
highlight("Operator", nil, Color3, "bold")
highlight("Keyword", nil, Color4, "bold")
highlight("Conditional", nil, Color4, "bold")
highlight("Repeat", nil, Color4, "bold")
highlight("WildMenu", Color5, Color4, nil)
highlight("Pmenu", Color5, Color4, nil)
highlight("PmenuSel", Color4, nil, nil)
highlight("PmenuThumb", Color5, Color4, nil)
highlight("Normal", Color5, Color4, nil)
highlight("SignColumn", Color5, nil, nil)
highlight("LineNr", nil, Color4, nil)
highlight("TSPunctDelimiter", nil, Color4, nil)
highlight("Delimiter", nil, Color6, "bold")
highlight("CursorColumn", "#CCFFFF", nil, nil)
highlight("String", nil, Color6, "bold")
highlight("@keyword.import.c", nil, "#008000", nil)

link("Conditional", "Operator")
link("NonText", "Comment")
link("TSFloat", "Number")
link("Folded", "Comment")
link("TSString", "String")
link("Whitespace", "Comment")
link("TSFuncMacro", "Macro")
link("TSParameterReference", "TSParameter")
link("TSComment", "Comment")
link("TSConditional", "Conditional")
link("TSNumber", "Number")
link("TSTag", "MyTag")
link("Operator", "Keyword")
link("TSConstant", "Constant")
link("CursorLineNr", "Identifier")
link("TSType", "Type")
link("TSPunctBracket", "MyTag")
link("TSTagDelimiter", "Type")
link("TSConstBuiltin", "TSVariableBuiltin")
link("TSNamespace", "TSType")
link("TSKeyword", "Keyword")
link("TSFunction", "Function")
link("Macro", "Function")
link("TSField", "Constant")
link("TelescopeNormal", "Normal")
link("TSProperty", "TSField")
link("TSOperator", "Operator")
link("TSPunctSpecial", "TSPunctDelimiter")
link("TSLabel", "Type")
link("TSRepeat", "Repeat")
link("TSParameter", "Constant")
link("Repeat", "Conditional")
link("@type.builtin.c", "Keyword")
link("Function", "Normal")
link("CursorLineNr", "LineNr")
link("CursorLine", "CursorColumn")
