vim.g.gruvbox_material_background='hard'
vim.g.gruvbox_material_enable_bold='1'
vim.g.gruvbox_material_diagnostic_line_highlight = '1'
vim.g.gruvbox_material_foreground='original'
vim.g.gruvbox_material_ui_contrast='high'
