#!/usr/bin/env racket
#lang racket
(require racket/match)
(current-subprocess-custodian-mode 'kill)

(match (current-command-line-arguments)
  [(vector) 
   (displayln "usage: borderless-chromium <url>" (current-error-port))
   (exit 1)]
  [(vector url)
   (match/values
     (subprocess #f #f #f (find-executable-path "chromium")
                 (format "--app=~a" url)) 
     [((? subprocess? subproc) _ _ _) (subprocess-wait subproc)]
     [(_ _ _ _) (raise-user-error "unreachable")])])

